version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "RawBucketName=\"classnotes-raw\" PdfBucketName=\"classnotes-pdfs\" TableName=\"classnotes-meta\""
image_repositories = []
